services:

  mongo:
    image: mongo:6
    build: 
      dockerfile: DockerFile-Mongo
    container_name: mongo-preloaded
    restart: unless-stopped
    ports:
      - '27018:27017'
    # volumes: 
    #   - ./mongo_init/restore.js:/docker-entrypoint-initdb.d/restore.js
    #   - ./mongo_export:/docker-entrypoint-initdb.d/export
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nest-app
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ./.env
  #   environment:
  #     - MONGODB
  #   depends_on:
  #     - mongo